title: panela_verde
description: Site de receitas livres. Instagram: @panela_verde E-mail: pavereceitas@gmail.com
logo: logo_panela_verde.png
show_downloads: false
google_analytics: G-SSJ6V6YYKL
theme: jekyll-theme-minimal
